### ISSUE TITLE
Strange behavior of input date field in patient register/edit forms

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#254]
The html5/angular implementation of the date input field seems broken:  If you change the year to '0000' our validation code will complain but once you click elsewhere on the form the year is changed to 0001 and error message goes away.  However, if you save the value, it updates in the database as 1901 (which is valid).

**Comment by jniles** [comment]
This is fascinating, and has my curiosity up.  Have you tried using the directive `ng-min` instead of `min` as a property of the DOM node?   I wonder if it would produce different results.

I'll take a look at this (for interest) after my work on fiscal year is complete.

**Comment by jmcameron** [comment]
I was able to verify that the date input field (with angular?) does honor 'min' and 'max' and the javascript/angular validation does mark it invalid.  However, when you click somewhere else, one of three things happens with invalid values:   (1) it leaves the value as invalid, (2) it fixes the value (internally?) and displays the minimum acceptable value, (3) if fixes the value and does not display the correct value.  I have not been able to nail down when it does which.

**Comment by jniles** [comment]
So, close to a year later, I've finally started rigourously looking into form validation and ran into this issue myself.  Here's what I've learned:

If you have a date input, such as this one:

```html
<input type="date" ng-model="Ctrl.date" name="date">
```

And you want to validate min and max attributes, here are some things you need to be aware of:
 1. Angular's ngMin and ngMax directives do not set the min and max attributes on the date input.  See this issue and the documentation.  This means that chrome does not render a calendar with dates that are blocked off (a nice UI feature) using ngMin and ngMax.
 2. The native HTML min and max attributes can be interpolated.  This means you can do this:

 ```html
<input type="date" min="{{ Ctrl.today }}">
```
 However, the date must be ISO string format (yyyy-MM-dd).  So, you must do this instead: 

 ```html
<input type="date" min="{{ Ctrl.today | date:'yyyy-MM-dd' }}">
```
which works.
 3. The ngMin and ngMax cannot be in ISO format, you get very, very weird results.  My "October 20, 2015" date resolves to "1856".  So this does not work:

 ```html
<input type="date" ng-min="{{ Ctrl.today | date:'yyyy-MM-dd' }}">
```
 This does: 

 ```html
<input type="date" ng-min="{{ Ctrl.today }}">
```
 4. Since we are using ISO format for the "min" and "max" date, sometimes you may need to set ng-min and min (or ng-max and max) to be different values: one to limit the view selection and the other to perform validation.

The final result looks strange, but this is how it must be laid out to work.  This is actual code from the exchange rate controller/view.
```html
<input name="date" type="date" class="form-bhima" ng-model="ExchangeCtrl.form.date" ng-disabled="!ExchangeCtrl.form.isOld" ng-max="{{ ExchangeCtrl.tomorrow }}" max="{{ ExchangeCtrl.today | date:'yyyy-MM-dd' }}">
```

Notice that I had to ensure the ngMax date was "anytime before tomorrow", but needed to limit the view to "anytime up to today".  This may not be the case for every controller, but this is what gave me the best results.

Just felt like this issue needed a follow-up.  I'm closing this now, and will reference issue #818 for a re-write using Angular's form validation.
