### ISSUE TITLE
Opening balance operation does not write lines into general ledger

### ISSUE THREAD

**Issue by DedrickEnc** [IMA-WorldHealth/bhima#274]
To be able of providing correct report, the financial status of the enterprise must be stored in posting journal or general ledger, which are accounting officials tools because all reports are scanning posting journal and general ledger to provide result.

**Comment by jniles** [comment]
After some discussion, it seems that writing to the general ledger will create more limitations than necessary.  Most accounting systems store the beginning balances in the period 0 and any reports requiring beginning balances should pick them up from period 0 in the period totals table.

I think this issue should be closed.

**Comment by jniles** [comment]
@DedrickEnc, I received more clarification on the issue here.

The opening balance for the first fiscal year is recorded in the period 0, in the period totals table.  This isn't actually a transaction because it is only a record of the valuation of your accounts at a given time.

For all other fiscal years, we have a design decision to make.  The second fiscal year can import opening balances into period 0 of the second year OR it can write them to the general ledger.  In a paper based accounting system, the chief accountant would have to write lines in the general ledger symbolizing the closing of all income and expense accounts, and transferring the balances to one or more balance accounts.

However, since we are writing our own accounting system, we have a choice - we can either write lines in the general ledger, or look them up from period 0.  The reports which need opening balances are only reports concerned with balance accounts (naturally).  These reports scan the period totals table as a convenience, instead of actually scanning the general ledger.  This reduces the load on the database, and enables rapid reporting.  Thus, there is no advantage to writing the opening balances in the general ledger, since most of our reports look at the period totals for there data, not the general ledger.

Reports such as debtor, employee, and patient standing reports must scan the general ledger, but these do not concern the opening balances since they are sub accounts.  We don't need to know the standing of all employees to know the standing of a single employee.

Therefore, it seems there is no advantage to bhima to write opening balances to the general ledger.  It is actually an inconvenience for those reports that only look at period totals to have to pick up data from the general ledger.

What do you think?  Ultimately, the accounting is only concerned that we include opening balances where appropriate, but it doesn't matter where we store them.  Practically, the period totals table seems to make the most sense.

**Comment by DedrickEnc** [comment]
The accounting logic prefers to write all transactions in an appropriate document, and this document can be a posting journal (temporary) or a general ledger (permanently).

Even at the beginning, opening balance will contain a set of transactions such as getting money from capital propre to buy a car or to construct a house and these are transactions and they must be recorded as all transaction.

To be more traditional, those initial transactions should be written in the posting journal and then posted to the general ledger.

There is an advantage to process that way, because all transaction writing process will be homogeneous and very tailed to the business logic because accountant process that way.

About the problem of reducing the database loading data time, I think that is not avoidable because with the time, our general ledger will have many data inside, even if we don't recorded initial transaction in it.

Also initial transaction are not so much then daily transactions to influence significantly the length of the general ledger table.

**Comment by jniles** [comment]
The current balance sheet queries do not query the general ledger.  They query the period_total table. For reference, see the file reports_proposed/balance_sheet.js in the main repository.

I will implement posting directly to the general ledger, as well as to the period_total table (since otherwise, we would have to do an expensive join to the GL to do the balance sheet report).

**Comment by jniles** [comment]
@DedrickEnc, is this still an issue?  Can we close it?

**Comment by DedrickEnc** [comment]
Yes, we can
