### ISSUE TITLE
Creating fiscal year creates 13 periods

### ISSUE THREAD

**Issue by jmcameron** [IMA-WorldHealth/bhima#339]
There seems to be a bug in the process to create a fiscal year.   It creates 13 periods.  The first period, with period number=0 has bogus dates (0000-00-00, etc).

**Comment by jniles** [comment]
That's on purpose.  Period 0 is where the beginning balances of a fiscal year are stored, since it doesn't really occur on one fiscal year or the other.  Once an account is closed, the values are written to the period_totals table in period 0.

Period 0 shouldn't have bogus dates, it should be the first day of the new fiscal year.  I'll look into that.

**Comment by jmcameron** [comment]
So I can avoid including this period in the query by avoiding budgets with period_number=0?

**Comment by jmcameron** [comment]
I have a fix ready for the edit budget page for this, assuming the answer is to avoid periods where period_number=0.

**Comment by jniles** [comment]
Yes. I believe that is an acceptable fix because the use of period 0 is an internal application decision the user will never see. It is useful for us, since looking at account balances for a particular fiscal year will automatically include beginning balances without any further logic.

**Comment by jniles** [comment]
In fact, the reasoning for this should be already documented in the fiscal year controller code on the server. I can improve it though, for future developers.

**Comment by jmcameron** [comment]
Ok, I've updated the edit budget PR to prevent use of budget periods where period_number=0.  So I'm closing this issue.
