### ISSUE TITLE
Migrate Currency and Date formats to ngLocale

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#569]
I'm not sure if we just didn't research properly or if this is a new addition to AngularJS, but there exists a module for proper configuration of dates and currencies called [ngLocale](http://www.angularjshub.com/examples/localization/simplelocalization/).  [Here](https://raw.githubusercontent.com/angular/angular.js/master/src/ngLocale/angular-locale_fr-be.js) is the Belgium French locale, which we could easily adapt to using Congolese Francs and remove the "intlcurrency" filter, which requires unsafe HTML injection.

Sticking to angular's way will let us write awesome code like `{{ new Date() | date:"Full Date" }}` and `{{ results.total | currency }}` without fear.  We may have to modify the currency filter slightly to ensure that we can use USD and FC in the same page.

**Comment by sfount** [comment]
I've been looking into this and it looks like it should be possible - there are a few complications as you mentioned re : multiple different currencies in one page but I'll throw together a prototype to make sure it works without being too obtrusive. 

FYR https://raw.githubusercontent.com/angular/angular.js/master/src/ngLocale/angular-locale_fr-cd.js they got this.

**Comment by jniles** [comment]
Yeah, @DedrickEnc thought that locale's translations were quite humorous, and they aren't exactly the formats we want them in. But it seem easy enough to roll our own!

Awesome, Iook forward to your prototype.

**Comment by sfount** [comment]
Quick progress review so far - one more decision we have to make and I will submit a pull request tomorrow. 

Using ngLocale for dates alone is definitely worth it, seeing the application now without a French date format doesn't look right, this is fairly easy to do and hasn't caused a problem. 
There are two options for serving a locale file, essentially a script that is run at the application startup that defines a number of formats and options within angular:
* Templating the correct locale file into the application HTML based on user preference and browser/system settings; this would require a server infrastructure change however this is something I think we should eventually decide to do
* Serve the locale file dynamically. I have done this because it is very similar to the way ng-translate works and respects patterns the application currently uses. 

The complication comes when displaying multiple different currencies on one page using the default currency filter - this is simply /not/ supported. ```{{amount | currency}}``` will display the format of the current locale. 

The solution I propose is to write a new currency filter that is essentially a fork of the native angular filter - it would use exactly the same locale settings and configuration but accept a setting to define which currency within BHIMA should be displayed. This would also mitigate the unsafe HTML binding issue. 

This then is the question:

__We currently model currencies formats within our database, angulars locale formats /also/ define how currencies should look - we should decide on where the currency filter should be getting information about how to format currency from. This either means__
* __Providing a link in the currency database to a locale file, each currency must reference a locale file that the currency filter will then fetch and use to render the currency__
* __Take the formatting attributes from the locale files and model them as part of the currency itself, this option changes the least about how BHIMA currently works; the currency filter will still make only one call to /finance/currencies/ and use the attributes stored to render currency.__

**Comment by sfount** [comment]
These are the fields that would be added to the currency database to allow the native angular currency filter to render them correctly; the fork of the currency filter would use the same methods but accept a BHIMA currency ID to select which rules to follow on a per element bases.

{
        "gSize": 3,
        "lgSize": 3,
        "maxFrac": 2,
        "minFrac": 2,
        "minInt": 1,
        "negPre": "-\u00a4",
        "negSuf": "",
        "posPre": "\u00a4",
        "posSuf": ""
}

For example:

```
{{ sale.total | currency:session.currency_id }}
```

**Comment by jniles** [comment]
@sfount, great work and discussion.

I'm in favor of extracting currency logic away from the database.  It would be similar to how we do languages.  The new table looks something like this in my mind:

| id | locale |
| --- | --- |
| 1 | 'en-usd' | 
| 2 | 'fr-cdf' |

The locale then maps to a `/currency/en-usd.json` route that is passed to ngLocale.  Currencies are lazy-loaded if an id is found that we don't have the ngLocale JSON description for.  @sfount, you obviously have more experience, so this be a bit naive ... but something along those lines.

Four reasons I like the JSON model versus the database model:
 1. We currently do not model translations in our database.  Given the similarity between the currency filter and the translate module, why not drop our model?  I can't think of why ours is superior.
 2. Imagine if we wish to upgrade ngLocale versions -- why might have to add/drop some columns.
 3. Upgrading to support more currencies only requires a simple INSERT command (for the new currency reference), plus a JSON --- similar to translate.
 4. Personal preference.  Databases are good for things that change often, this feels more like a one time configuration (which we sort of do in JSON already) than a database issue.

**Comment by sfount** [comment]
Very helpful to hear this, thanks @jniles. I agree that this separation of concerns is a good idea but after looking at it for so long it's good to hear a second opinion. 

JSON lazy loading suggestion is excellent as that will be how the locale files will have to be originally loaded. 

Something that the team should consider is that in an accounting tool like BHIMA the locale and the currency are actually completely separate - just because I want to see my dates in a french format doesn't mean that USD will ever turn into FC. In fact it may be important that our programmers can always assume a base currency will be displayed by the filter. Perhaps it would make sense for our application to completely separate currency formatting from language specific formatting.

**Comment by jniles** [comment]
A custom ``{{ amount | currency:currencyid }}` filter would do that correct?  In any case, each row still must have a currency ID and that currency id __must__ determine the currency formatting.

The only concern final concern is that error handling.  What happens if I delete `/currencies/fr-cdf.json`?  Does the application fail hard or default to USD?  My opinion is that we fail hard - it would be the same as deleting that currency ID in the database (which would break all links, etc).  You can't do multi-currency accounting without multiple currencies, and we shouldn't try to fake it.

**Comment by sfount** [comment]
Yes it would, using the filter namespace 'currency' would actually solve this issue as it wouldn't allow developers to make the mistake of using an ambiguous default locale currency. 

In my view it would make sense for ```{{ amount | currency }}``` to display the enterprises default currency (in our case dollars). 

I was thinking about this the other day and I think it wouldn't hurt to have a few tests run on server startup. An issue like this likely will be an initial server configuration issue. Things like:
* Are there translation files for each of the languages I support?
* Are there currency format files for all of my currencies?
* Do I actually have a ```wkhtmltopdf``` utility installed, if not, why not
* Do I actually have ```mail``` installed, if not, why not. etc. 

That being said I have a feeling that might be one of the things I'd like to see that would waste everyone's time and cause issues in deployment. 

I agree - if the client finds a discrepancy in currency it should mostly shut down.

**Comment by jniles** [comment]
I'm really concerned that `{{ amount | currency:non_existant_currencyid }}` should not map to `$amount`.  Perhaps `#amount`, or something that doesn't make sense, but still allows data (the amount) through -- but the user clearly should know that he/she is missing a crucial part of the transaction - the currency the transaction was made in!

I like the idea of startup tests; in fact, we already check for an exchange rate.  We could easily have a "application health" check on initial start page that does all those checks and reports a status (healthly, missing language, missing currency, partially installed, etc...).  We could loop this in with an install-type script to fix whatever the issue is.

**Comment by sfount** [comment]
Agreed. We could do something like MISSING_CURRENCY_SORRY_SORRY_PLEASE_FIX(13.50).

I like the idea of a page but we should make sure we [KISS](https://en.wikipedia.org/wiki/KISS_principle). 

The inspiration for this the excellent implementation of the mail plugin currently comes across an error if the server instance has no ```mail``` command, it then tries again every x minutes indefinitely for the life of BHIMA. Of course we know this massive issue should either stop the server or report that the mail plugin is not supported and remove all communication. That's on a list I have somewhere to make an issue about shortly.

**Comment by jniles** [comment]
I like how you just derailed the thread to beat the mail plugin to death :D.

Make sure you make the issue in the [mail plugin repository](https://github.com/IMA-WorldHealth/bhima-plugin-mail).

**Comment by sfount** [comment]
It was like a *note to self*, I hope the mail plugin survives. 
You are correct though! If anyone has any further comments on the currency/locale relationship please add them following! If not pull request to follow shortly.
