### ISSUE TITLE
UI Freezing on All Transctions State report

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#700]
On the "All Transactions State" report (`#/reports/global_transaction/`), the UI noticably lags for ~ 7 seconds.  This is shown clearly in the chrome dev tools - while the DOM content is loaded in ~900ms, the actual page load (after templating) is ~6.91 seconds.  See below.

![ui-freeze](https://cloud.githubusercontent.com/assets/896472/9699342/2ba56224-53d7-11e5-8755-7d5a6f5a0554.png)

Most likely, our ng-repeat on accounts is taking far to much time.  We can try to speed this up by using [track by](https://docs.angularjs.org/api/ng/directive/ngRepeat) and [one time data-bindings](http://www.bennadel.com/blog/2759-exploring-one-time-bindings-in-angularjs-1-3.htm).  Someone should investigate these options to see if they would work.

If all else fails, we can look at different measures, such as using typeahead.

**Comment by sfount** [comment]
I've run a few performance tests on this issue. 

You are correct in identifying the performance bottleneck as the repeating options - however it is nothing to with either how elements are tracked or data binding. 

I experimented using angular native [one time data binding](https://docs.angularjs.org/guide/expression#one-time-binding) to ensure it was nothing to do with multiple updates on each digest. 
```<option ng-repeat="account in ::accounts.data"></option>```
This still causes a significant time delay - as I understand it this is simply because angular is creating and inserting thousands of DOM elements _individually_. 

As far as I can tell there are a few options:
* Create a directive that takes the array of accounts, compiles them into one big element (the select) and inserts this into the DOM in one action. I've proven this works before with the 'reportGroupCompile' directive even though I believe that was never actually used. This still just provides a big select of accounts however it will process instantly. 

* Typeahead on accounts 

* Account search directive similar to the patient search directive - this could be used anywhere we must define an account and provide additional features. For example typeahead to lookup accounts you already know the numbers for and click a 'view all/ reference' button to be able to search through all the accounts (in a modal or something). 

Another point worth making here is the current code calls a formatting method in the template 
```{{formatAccount(acc)}}```
This is __not__ the reason for the initial slow UI however this method is called multiple times on every digest loop. This results in:

* Initial page load : **14976** calls to formatAccount
* Every time anything changes : **~5000** calls to formatAccount

A more efficient practice here would be to format the account strings _once_ as soon as the data is downloaded, this account string could then be stored in each accounts object and displayed without calculation ```{{acc.formattedString}}```

**Comment by jniles** [comment]
@sfount, Great work!  Did you try `track by`?

I'm not too surprised that the one-time data binding didn't do too much -- it seems more for app control than for optimizations.  However, did you try `<option ng-repeat="::account in accounts.data">`?  I get the impression that `::accounts` would remove listeners on the list, but not the dom nodes within the list.

**Comment by sfount** [comment]
I did try that! Logic dictates that it would do something but it is not supported syntax. 

The two supported variations in ng-repeat are 
```<option ng-repeat="account in ::acounts.data">{{account.name}}</option>```

```<option ng-repeat="account in accounts.data">{{::account.name}}</option>```

The first one will only load the and listen on the array once, one it has been loaded adding or removing elements will not change the ng-repeat. 

The second will update for changes in the array however the individual attribute is one way bound ignoring any updates on that. 

Neither reduce the massive task of individually inserting ~5000 DOM nodes individually.

**Comment by sfount** [comment]
@jniles referenced a very recent upgrade to [ng-options](https://code.angularjs.org/1.4.4/docs/api/ng/directive/ngOptions). 

This actually allows options to disabled using the 'disable when' syntax

```<select ng-options="account.displayString disable when (account.account_type_id === 3) for account in accounts.data" ng-model="session.selectedAccount"></select>```

This loads instantly and completely mitigates the DOM issue. I'll submit a pull request with a suggestion for this is done shortly.

**Comment by jniles** [comment]
Awesome!  Glad this worked.
