### ISSUE TITLE
Optimize gulp build time

### ISSUE THREAD

**Issue by jniles** [IMA-WorldHealth/bhima#750]
It would be nice if we could optimize our build times a little more, without letting our standards (jshint. translations, etc) slip too significantly.

I propose that we move utilities such as the JSON key validation @jmcameron built, jshint, and uglify out of the standard build.  For development, these are not critical, and we do a lot of development.  We can still expose these features for pre-PR checks by using a different gulp task (`gulp build-complete` or something).

The disadvantage with this proposal is that it will not enforce either balanced translations or keeping with jshint standards.  The reviewers of pull requests should probably validate that these check pass, or we could build it into a Travis build process.

What do you all think? cc @IMA-WorldHealth/owners

**Comment by jmcameron** [comment]
I have mixed feelings about this. On one hand, I see and understand the issue of slowing down builds affecting productivity.   But I also feel that corrections (language, jshint, etc) that are not caught early are likely to stick around much longer than anyone wishes.   Fixing these issues when they first come up is less painful and lower-friction than doing it later -- so this would argue for doing most/all of these checks during all builds.   If these are put in a pre-PR check, I think it should not be easy to skip!

Regarding the translation checks, I think it should be possible to only check the translation files when they have actually changed.  Not sure exactly how to do that but I think it should not be too hard since we can do it programmatically in gulp.

-Jonathan C

**Comment by jniles** [comment]
Unfortunately, gulp-watch still breaks while trying to lint JSON files.  I guess that could be another research questions, but when translation files change, the watch loop breaks, killing gulp anyway. :(

I appreciate the feedback!  I think we are starting to get more structure to our PRs, seen in recent decisions (#719).  For the simple productivity boost, I'd be willing to give it a try and reverting if we do end up with painful translation/jshint issue.  At the moment though, my code to compile ratio has skyrocketed (especially for server code)!

**Comment by jniles** [comment]
After some tests, the translation file linting was negligible.  The build has been optimized slightly by removing linting from the build, replaced by a warning to lint before submitting a PR.  I'll be working on a script for Travis to lint before approving a merge.

Closing this since it has landed in development.
